version: '3.4'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-3.0
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./RM8Back.sln && dotnet publish ./RM8Back.sln -c Release -o ./obj/Docker/publish"
